# -*- coding: utf-8 -*-
"""Lista 100 exercícios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMTLtQ8XwUzQ9zYYFJv0hCJHGxQlCxtk

# Lista de 100 Exercícios de Python

Seja bem-vindo(a) a esta trilha prática de exercícios em Python.

Esta atividade foi organizada com o objetivo de fortalecer sua aprendizagem em lógica de programação, desenvolvimento de algoritmos e resolução de problemas computacionais por meio da prática progressiva. Ao longo deste material, você deverá resolver os **100 exercícios propostos**, estruturados em nível crescente de complexidade, contemplando desde conceitos introdutórios até o uso de listas, funções e dicionários.

Para a realização da atividade, é fundamental que cada solução seja desenvolvida com atenção à **clareza, organização e legibilidade do código**.

Ao finalizar a resolução dos exercícios, salve seus códigos em um **repositório no GitHub** e envie o link no Moodle.

## Exercício 1
Receba um nome e exiba.
"""

nome = input("Digite um nome: ")
print(f"Nome: {nome}")

"""## Exercício 2
Receba duas notas e calcule a média.
"""

def calculo_media(nota1, nota2):
  media = (nota1 + nota2) // 2
  return media # Retorna o valor da função

nota1 = float(input("Digite uma nota: "))
nota2 = float(input("Digite outra nota: "))
# float = mostrar números com casas decimais

media = calculo_media(nota1, nota2)
print(f"Média: {media: .2f}")
# .2f = exibe duas casas decimais para float

"""## Exercício 3
Receba um número e mostre o dobro.
"""

def calculo_dobro(numero):
  dobro = (numero) * 2
  return dobro

numero = int(input("Digite um número: "))
dobro = calculo_dobro(numero)
print(f"O dobro desse número é: {dobro}")

"""## Exercício 4
Receba um número e mostre o triplo.
"""

def calculo_triplo(numero):
  triplo = (numero) * 3
  return triplo

numero = int(input("Digite um número: "))
triplo = calculo_triplo(numero)
print(f"O triplo, desse número é: {triplo}")

"""## Exercício 5
Receba idade e diga se é maior de idade.
"""

idade = int(input("Digite uma idade: "))
if (idade) >= 18:
  print(f"É maior de idade.")
else:
  print(f"É menor de idade.")

"""## Exercício 6
Receba um número e diga se é par ou ímpar.
"""

# Dúvida no exercício

def calculo_par_impar(numero):
  if numero // 2 == 0:
    return f"{numero} é par"
  else:
    return f"{numero} é ímpar"

numero = int(input("Digite um número: "))
print(calculo_par_impar(numero))

"""## Exercício 7
Receba três números e mostre o maior.
"""

numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))
numero3 = float(input("Digite o terceiro número: "))
maior = numero1

if numero2 > maior:
    maior = numero2

if numero3 > maior:
    maior = numero3

print("O maior número é:", maior)

"""## Exercício 8
Mostre a tabuada de um número até 10.
"""

numero = int(input("Digite um número: "))
for i in range(1,11):
  print(f"{numero} x {i} = {numero*i}")

"""## Exercício 9
Mostre números de 1 a 10.
"""

for i in range(1, 11):
    print(i)

"""## Exercício 10
Mostre números de 10 a 1.
"""

for i in range(10, 0, -1):
    print(i)

"""## Exercício 11
Some números de 1 a 100.
"""

soma = 0

for i in range(1, 101):
    soma += i

print("A soma é:", soma)

"""## Exercício 12
Conte números pares de 1 a 50.
"""

for i in range(1, 51):
    if i % 2 == 0:
        print(i)

"""## Exercício 13
Crie lista com 5 números e mostre.
"""

lista = [8, 5, 3, 1, 4]
print(lista)

"""## Exercício 14
Mostre o maior da lista.
"""

numeros = [8, 5, 3, 1, 4]

maior = numeros[0]
for n in numeros:
    if n > maior:
        maior = n
print(f"O maior número da lista é:", maior)

"""## Exercício 15
Mostre soma da lista.
"""

lista = [8, 5, 3, 1, 4]
soma = 0

for n in lista:
  soma += n

print(soma)

"""## Exercício 16
Receba palavra e inverta.
"""

palavra = input("Digite uma palavra: ")
inverso = "" # String vazia inverte a palavra

for letra in palavra:
  inverso = letra + inverso

print(inverso)

"""## Exercício 17
Conte letras de uma palavra.
"""

palavra = input("Digite uma palavra: ")
numeros = len(palavra)

print("Quantidade de letras:", numeros)

"""## Exercício 18
Conte vogais.
"""

palavra = input("Digite uma palavra: ")
vogais = "aeiouAEIOU"

contador = 0
for letra in palavra:
  if letra in vogais:
    contador += 1

print("Quantidade de vogais:", contador)

"""## Exercício 19
Conte palavras de uma frase.
"""

frase = input("Digite uma frase: ")

palavras = frase.split()  # separa a frase em uma lista de palavras, usa espaço
quantidade = len(palavras)

print("Número de palavras:", quantidade)

"""## Exercício 20
Função que soma dois números.
"""

def soma_numeros(numero1, numero2):
  soma = (numero1) + (numero2)
  return soma

numero1 = int(input("Digite um número: "))
numero2 = int(input("Digite outro número: "))

resultado = soma_numeros(numero1, numero2)

print(f"A soma dos números é: {resultado}")

"""## Exercício 21
Função que retorna maior número.
"""

def maior_numero(lista):
  return max(lista)

numeros = [8, 5, 4, 6]
print(maior_numero(numeros))

"""## Exercício 22
Função que verifica par.
"""

def numero_par(numero):
  return numero % 2 == 0

numero = int(input("Digite um número: "))

if numero_par(numero):
  print("É par.")
else:
  print("Não é par.")

"""## Exercício 23
Lista com números pares.
"""

pares = [2, 22, 16, 44, 8]
print(pares)

"""## Exercício 24
Remover duplicados da lista.
"""

lista = [1, 1, 2, 3, 3, 4, 5, 5]

remover_duplicados = list(set(lista)) # apenas remove duplicatas
print(remover_duplicados)

"""## Exercício 25
Ordenar lista.
"""

numeros = [8, 5, 3, 1, 4]
numeros.sort()

print(numeros)

"""## Exercício 26
Contar ocorrência de número.
"""

lista = [1, 1, 2, 3, 3, 4, 5, 5]

contagem = {}

for n in lista:
  if n in contagem:
    contagem[n] += 1
  else:
    contagem[n] = 1

print(f"Ocorrência de números: ", contagem)

"""## Exercício 27
Somar apenas pares da lista.
"""

numeros = [2, 7, 16, 33, 8]

def soma_pares(lista):
  soma = 0
  for n in lista:
    if n % 2 == 0:
      soma += n
  return soma

print(soma_pares(numeros))

"""## Exercício 28
Filtrar maiores que 10.
"""

numeros = [6, 8, 12, 7, 20, 60]
resultado = []

for n in numeros:
    if n > 10:
        resultado.append(n)

print(resultado)

"""## Exercício 29
Criar lista com range.
"""

numeros = list(range(1, 11))
print(numeros)

"""## Exercício 30
Somar números digitados até 0.
"""

soma = 0

while True:
    numero = int(input("Digite um número: "))

    if numero == 0:
        break

    soma += numero

print("Soma total:", soma)

"""## Exercício 31
Contar números positivos.
"""

numeros = [-3, -2, -1, 0, 1 ,2, 3]

contador = 0
for n in numeros:
    if n > 0:
        contador += 1

print("Quantidade de números positivos:", contador)

"""## Exercício 32
Calcular fatorial.
"""

numero = int(input("Digite um número: "))

print(f"{numero}! = {numero}", end= "")

fatorial = numero
for i in range(numero-1, 0, -1):
  print(f" x {i}", end="")
  fatorial *= i

print(f" = {fatorial}")

"""## Exercício 33
Verificar número primo.
"""

numero = int(input("Digite um número: "))

contador = 0
divisor = 1
while(divisor <= numero):
  if numero % divisor == 0:
    contador += 1
  divisor += 1

if contador == 2:
  print("Número é primo")
else:
  print("Número não é primo")

"""## Exercício 34
Gerar lista de primos até N.
"""

def numero_primo(num):
    if num < 2:
        return False

    for i in range(2, num):
        if num % i == 0:
            return False

    return True


N = int(input("Digite um número: "))

primos = []

for numero in range(2, N + 1):
    if numero_primo(numero):
        primos.append(numero)

print(primos)

"""## Exercício 35
Somar elementos pares.
"""

numeros = [2, 22, 16, 44, 8]

def soma_pares(lista):
  soma = 0
  for n in lista:
    if n % 2 == 0:
      soma += n
  return soma

print(soma_pares(numeros))

"""## Exercício 36
Converter Celsius para Fahrenheit.
"""

celsius = float(input("Digite a temperatura em Celsius: "))

fahrenheit = (9/5) * celsius + 32

print("Temperatura em Fahrenheit:", fahrenheit)

"""## Exercício 37
Contar letras maiúsculas.
"""

texto = input("Digite um texto: ")

contador = 0

for letra in texto:
    if letra >= 'A' and letra <= 'Z':
        contador = contador + 1

print("Maiúsculas:", contador)

"""## Exercício 38
Remover espaços da string.
"""

# string é um dado usado para representar texto
texto = input("Digite um texto: ")

print(texto.replace(" ", "")) # replace substitui parte da string por outra

"""## Exercício 39
Verificar palíndromo.
"""

numero = int(input("Digite um número: "))
n = numero
inverso = 0

while n > 0:
    inverso = inverso * 10 + n % 10
    n = n // 10

if inverso == numero:
    print(f"{numero} é palíndromo")
else:
    print(f"{numero} não é palíndromo")

"""## Exercício 40
Substituir palavra em frase.
"""

frase = "Irei viajar hoje."

nova_frase = frase.replace("hoje", "amanhã")

print(nova_frase)

"""## Exercício 41
Receba uma lista e mostre apenas os números pares.
"""

numeros = [2, 7, 16, 33, 8]

def mostrar_pares(lista):
    pares = []
    for n in lista:
        if n % 2 == 0:
            pares.append(n)
    return pares

print("Números pares:", mostrar_pares(numeros))

"""## Exercício 42
Receba uma lista e mostre apenas os números ímpares.
"""

numeros = [2, 7, 16, 33, 8]

def mostrar_impares(lista):
    impares = []
    for n in lista:
        if n % 2 != 0:
            impares.append(n)
    return impares

print("Números ímpares:", mostrar_impares(numeros))

"""## Exercício 43
Calcule a média de uma lista de números.
"""

numeros = [2, 3, 5, 22]

media = sum(numeros) / len(numeros)

print("A média é:", media)

"""## Exercício 44
Mostre o menor valor de uma lista.
"""

numeros = [8, 5, 3, 1, 4]

menor = numeros[0]
for n in numeros:
    if n < menor:
        menor = n
print(f"O menor número da lista é:", menor)

"""## Exercício 45
Multiplique todos os elementos de uma lista.
"""

numeros = [1, 5, 10]

resultado = 1
for n in numeros:
    resultado *= n

print("Multiplicação dos elementos:", resultado)

"""## Exercício 46
Crie uma lista com os quadrados dos números de 1 a 10.
"""

quadrados = []

for n in range(1, 11):
    quadrados.append(n * n)

print(quadrados)

"""## Exercício 47
Crie uma lista com os números pares de 1 a 20.
"""

pares = list(range(2, 21, 2))  # começa em 2, vai até 20, pulando de 2 em 2
print(pares)

"""## Exercício 48
Remova valores negativos de uma lista.
"""

numeros = [-3, -2, -1, 0, 1, 2, 3]

positivos = []

for n in numeros:
    if n >= 0:
        positivos.append(n)

print(positivos)

"""## Exercício 49
Conte quantos números maiores que 10 existem na lista.
"""

numeros = [2, 10, 20, 6, 45]
print(numeros)

contador = 0

for n in numeros:
    if n > 10:
        contador += 1

print("Quantidade de números maiores que 10:", contador)

"""## Exercício 50
Crie uma lista invertida.
"""

lista = [1, 2, 3, 4, 5]

lista.reverse()

print(lista)

"""## Exercício 51
Verifique se um elemento existe na lista.
"""

lista = [2, 5, 10, 15, 20]

numero = int(input("Digite um número: "))

if numero in lista:
    print("Existe na lista.")
else:
    print("Não existe na lista.")

"""## Exercício 52
Conte quantas vezes um número aparece na lista.
"""

lista = [2, 2, 5, 6, 6, 8, 10, 10, 10]

numero = int(input("Digite um número: "))

print("O número aparece", lista.count(numero), "vezes.")

"""## Exercício 53
Junte duas listas em uma só.
"""

lista1 = [0, 1, 2]
lista2 = [3, 4, 5]

juncao = lista1 + lista2

print(juncao)

"""## Exercício 54
Retorne a interseção entre duas listas.
"""

lista1 = [2, 3, 5, 6]
lista2 = [5, 6, 7, 8]

intersecao = []

for n in lista1:
    if n in lista2:
        intersecao.append(n)

print(intersecao)

"""## Exercício 55
Retorne a diferença entre duas listas.
"""

lista1 = [2, 3, 5, 6]
lista2 = [5, 6]

diferenca = []

for n in lista1:
    if n not in lista2:
        diferenca.append(n)

print(diferenca)

"""## Exercício 56
Crie uma função que retorna o maior valor de uma lista.
"""

def maior_valor(lista):
    maior = lista[0]

    for n in lista:
        if n > maior:
            maior = n

    return maior

numeros = [2, 3, 8, 7, 6, 5, 4]

print(maior_valor(numeros))

"""## Exercício 57
Crie uma função que retorna o menor valor de uma lista.
"""

def menor_valor(lista):
    menor = lista[0]

    for n in lista:
        if n <= menor:
            menor = n

    return menor

numeros = [2, 3, 8, 7, 6, 5, 4]

print(menor_valor(numeros))

"""## Exercício 58
Crie uma função que retorna a média de uma lista.
"""

def media_lista(lista):
    soma = 0

    for n in lista:
        soma += n

    media = soma / len(lista)
    return media

numeros = [2, 3, 8, 7, 6, 5, 4]

print(media_lista(numeros))

"""## Exercício 59
Crie uma função que remove duplicados de uma lista.
"""

def remove_duplicados(lista):
    nova_lista = []

    for n in lista:
        if n not in nova_lista:
            nova_lista.append(n)

    return nova_lista

numeros = [2, 2, 3, 8, 7, 7, 6, 5, 5, 4]

print(remove_duplicados(numeros))

"""## Exercício 60
Crie uma função que retorna apenas números positivos.
"""

def positivos(lista):
    positivo = []

    for n in lista:
        if n > 0:
            positivo.append(n)

    return positivo

numeros = [-3, -2, -1, 0, 1, 2, 3]

print(positivos(numeros))

"""## Exercício 61
Criar dicionário com nome e idade.
"""

dicionario = {
    'Nome': 'Aryani',
    'Idade': 21
}

print(dicionario)

"""## Exercício 62
Acessar valor do dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21
}

print(f"O nome é: ", dicionario["Nome"])
print(f"A idade é: ", dicionario["Idade"])

"""## Exercício 63
Adicionar item ao dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21
}

dicionario["Altura"] = 1.63

print(dicionario)

"""## Exercício 64
Remover item do dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21,
    "Altura": 1.63
}

del dicionario["Altura"]

print(dicionario)

"""## Exercício 65
Iterar sobre dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21,
    "Altura": 1.63
}

for item in dicionario:
    print(item, ":", dicionario[item])

"""## Exercício 66
Verificar se chave existe no dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21,
    "Altura": 1.63
}

if "Nome" in dicionario:
    print("Chave existe.") # chave = key
else:
    print("Chave não existe.")

"""## Exercício 67
Contar quantidade de itens no dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21,
    "Altura": 1.63
}

print(len(dicionario))

"""## Exercício 68
Mostrar apenas valores do dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21,
    "Altura": 1.63
}

for valor in dicionario.values():
    print(valor)

"""## Exercício 69
Mostrar apenas chaves do dicionário.
"""

dicionario = {
    "Nome": "Aryani",
    "Idade": 21,
    "Altura": 1.63
}

for chave in dicionario.keys():
    print(chave)

"""## Exercício 70
Criar dicionário com lista de valores.
"""

dicionario = {
    "Nomes": ["João", "Maria"],
    "Idades": [21, 20]
}

print(dicionario)

"""## Exercício 71
Somar valores de um dicionário.
"""

idades = {
    "João": 21,
    "Maria": 20,
    "Ana": 19
}

print(sum(idades.values()))

"""## Exercício 72
Encontrar maior valor no dicionário.
"""

idades = {
    "João": 21,
    "Maria": 20,
    "Ana": 19
}

print(max(idades.values()))

"""## Exercício 73
Criar lista de dicionários com nomes e idades.
"""

pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 19}
]

print(pessoas)

"""## Exercício 74
Filtrar pessoas maiores de idade.
"""

pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

maiores = []

for pessoa in pessoas:
    if pessoa["Idade"] >= 18:
        maiores.append(pessoa)

print(maiores)

"""## Exercício 75
Contar quantos itens atendem condição em lista de dicionários.
"""

pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

contador = 0

for pessoa in pessoas:
    if pessoa["Idade"] >= 18:
        contador += 1

print(f"Quantas pessoas são maiores de idade: ", contador)

"""## Exercício 76
Ordenar lista de dicionários por idade.
"""

def contar_idade(pessoa):
    return pessoa["Idade"]


pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

pessoas.sort(key=contar_idade) # sort organiza por ordem crescente

print(pessoas)

"""## Exercício 77
Buscar elemento por nome em lista de dicionários.
"""

pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

nome_busca = input("Digite um nome: ")

for pessoa in pessoas:
    if pessoa["Nome"] == nome_busca:
        print(pessoa)

"""## Exercício 78
Atualizar idade em lista de dicionários.
"""

pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

nome_busca = input("Digite um nome: ")
nova_idade = int(input("Digite uma nova idade: "))

for pessoa in pessoas:
    if pessoa["Nome"] == nome_busca:
        pessoa["Idade"] = nova_idade

print(pessoas)

"""## Exercício 79
Remover elemento da lista de dicionários.
"""

pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

nome_busca = input("Digite um nome para remover: ")

for pessoa in pessoas:
    if pessoa["Nome"] == nome_busca:
        pessoas.remove(pessoa)
        break

print(pessoas)

"""## Exercício 80
Criar função que recebe lista de dicionários e retorna média de idades.
"""

def media_idades(pessoas):
    soma = 0

    for pessoa in pessoas:
        soma += pessoa["Idade"]

    return soma / len(pessoas)


pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

print(f"A média de idades é: ", media_idades(pessoas))

"""## Exercício 81
Criar função que retorna maior idade.
"""

def maior_idade(pessoas):
    maior = pessoas[0]["Idade"]

    for pessoa in pessoas:
        if pessoa["Idade"] > maior:
            maior = pessoa["Idade"]

    return maior


pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

print(f"A maior idade é: ", maior_idade(pessoas))

"""## Exercício 82
Criar função que retorna menor idade.
"""

def menor_idade(pessoas):
    menor = pessoas[0]["Idade"]

    for pessoa in pessoas:
        if pessoa["Idade"] <= menor:
            menor = pessoa["Idade"]

    return menor


pessoas = [
    {"Nome": "João", "Idade": 21},
    {"Nome": "Maria", "Idade": 20},
    {"Nome": "Ana", "Idade": 17}
]

print(f"A menor idade é: ", menor_idade(pessoas))

"""## Exercício 83
Converter lista de nomes em dicionário com índice.
"""

nomes = ["João", "Maria", "Ana"]

dicionario = {}
i = 1

for nome in nomes:
    dicionario[i] = nome
    i += 1

print(dicionario)

"""## Exercício 84
Criar dicionário a partir de duas listas.
"""

nomes = ["João", "Maria", "Ana"]
idades = [21, 20, 17]

dicionario = {}

for i in range(len(nomes)):
    dicionario[nomes[i]] = idades[i]

print(dicionario)

"""## Exercício 85
Inverter chave e valor de um dicionário.
"""

pessoa = {
    "João": 21,
    "Maria": 20,
    "Ana": 17
}

inversao = {}

for chave in pessoa:
    inversao[pessoa[chave]] = chave

print(inversao)

"""## Exercício 86
Contar frequência de letras em uma palavra usando dicionário.
"""

palavra = input("Digite uma palavra: ")

frequencia = {}

for letra in palavra:
    if letra in frequencia:
        frequencia[letra] += 1
    else:
        frequencia[letra] = 1

print(f"A frequência das letras na palavra é: ", frequencia)

"""## Exercício 87
Contar frequência de palavras em frase.
"""

frase = input("Digite uma frase: ")

frequencia = {}

palavras =  frase.split() # split separa a string em partes

for palavra in palavras:
    if palavra in frequencia:
        frequencia[palavra] += 1
    else:
        frequencia[palavra] = 1

print(f"A frequência das palavras na frase é: ", frequencia)

"""## Exercício 88
Agrupar números pares e ímpares em dicionário.
"""

numeros = [2, 7, 10, 13, 15, 20]

resultado = {
    "pares": [],
    "impares": []
}

for n in numeros:
    if n % 2 == 0:
        resultado["pares"].append(n)
    else:
        resultado["impares"].append(n)

print(resultado)

"""## Exercício 89
Criar função que verifica se todos valores são positivos.
"""

def valores_positivos(lista):
    for n in lista:
        if n <= 0:
            return False
    return True

numeros = [-2, -1, 2, 7, 10, 13, 15, 20]

print(f"A afirmação: 'Todos os valores são positivos' é: ", valores_positivos(numeros))

"""## Exercício 90
Criar função que retorna apenas valores únicos de lista.
"""

# Números que não se repetem
def valores_unicos(lista):
    nova_lista = []

    for n in lista:
        if n not in nova_lista:
            nova_lista.append(n)

    return nova_lista


numeros = [1, 1, 2, 3, 4, 4, 5, 5]

print(valores_unicos(numeros))

"""## Exercício 91
Criar função que recebe lista e retorna apenas pares.
"""

def numeros_pares(lista):
    pares = []

    for n in lista:
        if n % 2 == 0:
            pares.append(n)

    return pares


numeros = [1, 2, 3, 4, 5]

print(f"Lista com números pares: ", numeros_pares(numeros))

"""## Exercício 92
Criar função que soma lista usando reduce ou loop.
"""

def soma_lista(lista):
    soma = 0

    for n in lista:
        soma += n

    return soma


numeros = [1, 2, 3, 4, 5]

print(f"A soma da lista é: ", soma_lista(numeros))

"""## Exercício 93
Criar função que multiplica todos valores da lista.
"""

def multiplicacao_lista(lista):
    resultado = 1

    for n in lista:
        resultado *= n

    return resultado


numeros = [1, 2, 3, 4, 5]

print(f"O resultado da multiplicação da lista é: ", multiplicacao_lista(numeros))

"""## Exercício 94
Criar função que retorna lista invertida.
"""

def inversao_lista(lista):
    invertido = []

    for n in lista:
        invertido.insert(0, n)

    return invertido


numeros = [1, 2, 3, 4, 5]

print(inversao_lista(numeros))

"""## Exercício 95
Criar função que verifica se lista está ordenada.
"""

def esta_ordenada(lista):
    for i in range(len(lista) - 1):
        if lista[i] > lista[i + 1]:
            return False
    return True


numeros = [1, 2, 3, 4, 5]

print(f"A afirmação = 'A lista está ordenada' é:", esta_ordenada(numeros))

"""## Exercício 96
Criar função que remove valores negativos.
"""

def remove_negativos(lista):
    nova_lista = []

    for n in lista:
        if n >= 0:
            nova_lista.append(n)

    return nova_lista


numeros = [-3, -2, -1, 0, 1, 2, 3]

print(remove_negativos(numeros))

"""## Exercício 97
Criar função que junta duas listas.
"""

def juntar_listas(lista1, lista2):
    return lista1 + lista2

lista1 = [0, 1, 2]
lista2 = [3, 4, 5]

print(juntar_listas(lista1, lista2))

"""## Exercício 98
Criar função que retorna interseção de listas.
"""

def intersecao(lista1, lista2):
    resultado = []

    for n in lista1:
        if n in lista2:
            resultado.append(n)

    return resultado


lista1 = [2, 3, 5, 6]
lista2 = [5, 6, 7, 8]

print(intersecao(lista1, lista2))

"""## Exercício 99
Criar função que retorna diferença entre listas.
"""

def diferenca(lista1, lista2):
    resultado = []

    for n in lista1:
        if n not in lista2:
            resultado.append(n)

    return resultado


lista1 = [2, 3, 5, 6]
lista2 = [5, 6]

print(diferenca(lista1, lista2))

"""## Exercício 100
Criar função que conta elementos únicos.
"""

def contar_unicos(lista):
    return len(set(lista))


numeros = [1, 1, 2, 3, 3, 4, 5, 5, 6]

print(contar_unicos(numeros))